spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee-tax
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update
  main:
    banner-mode: "off"

server:
  port: 8080